config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "comments#index"
  resources :comments, except: [:edit, :update]
  get "prix", to: "pages#prices"
  get "about", to: "pages#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :index

  def index
    @comments = policy_scope(Comment).order(created_at: :desc)
    @comment = Comment.new
    authorize @comment
  end

  def new
    @comment = Comment.new
    authorize @comment
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to root_path
    else
      render :new
    end
    authorize @comment
  end

  def edit
  end

  def update
    @comment.update(comment_params)
    redirect_to root_path
    authorize @comment
  end

  def destroy
    @comment.destroy
    redirect_to root_path
    authorize @comment
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content, :user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def prices
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/index.html.erb
<div class="main_content">
  <div class="presentation pres">
    <%= image_tag("MSyndicLogo.png", alt: "logo") %>
    <div class="infos">
      <div class="pub">
        <div class="title">
          <h1 class='word1'>Monsieur</h1><h1 class='word2'>SYNDIC</h1>
        </div>
        <h2 style='margin: 5px'> Un cabinet éthique et novateur</h2>
        <br>
        <div class="contenu">
          <p>Notre cabinet indépendant s’attache à développer un travail de qualité tout en valorisant la proximité et la disponibilité indispensables à notre métier de services. Une équipe autonome et passionée est l’un des moteurs de notre entreprise à taille humaine.</p>
        </div>
        <%if @comments.any?%>
        <div class="actu">
          <h2>Actualités</h2>
          <br>
          <ul>
            <% @comments.each do |comment| %>
            <li><%= comment.content %>
                <% if policy(comment).destroy? %>
                  <%= button_to comment_path(comment), class: 'trash',
                    method: :delete,
                    data: { confirm: "Are you sure?" } do%>
                    <i class="fa-regular fa-trash-can"></i>
                    <% end %>
                <% end %>
            </li>
            <br>
            <% end %>
          </ul>
          <br>
        </div>
        <%end%>
        <% if user_session %>
        <div class="add">
          <%= link_to new_comment_path, class: 'add' do%>
            <i class="fa-solid fa-plus"></i>
          <% end %>
        </div>
        <%end%>
      </div>
    </div>
  </div>
  <div class="where">
    <div class="title">
        <h1 class='word1'>Monsieur</h1><h1 class='word2'>SYNDIC</h1>
    </div>
    <h2 style='margin: 5px'> Un cabinet éthique et novateur</h2>
    <div class="horaires">
      <h4 style='margin: 5px'>
        <i class="fa-regular fa-clock" style='margin-right: 10px'></i>
        "Horaires: Lundi - Vendredi, 9:00-12:00, 14:00 - 17:00"
      </h4>
    </div>
    <div class="map">
      <h4 style='font-weight: bolder'>137, Boulevard Baille 13005 Marseille </h4>
      <h4 style='font-weight: bolder'>07.87.32.80.06</h4>
      <div class="metro">
        <div class="m1"><h4 class='name'>M1</h4></div>
        <p class='ligne'>Sortie Métro Baille</p>
      </div>
      <br>
      <div class="metro">
        <div class="m1"><h4 class='name'>54</h4></div>
        <p class='ligne'>Arrêt Baille-Vertus</p>
      </div>
      <br>
      <iframe style='border-radius: 10px' src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2904.2352418355304!2d5.389844712205747!3d43.28839507100127!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12c9c0a86bf0e9fd%3A0x37666e6272b7e69!2s137%20Bd%20Baille%2C%2013005%20Marseille!5e0!3m2!1sfr!2sfr!4v1710519090008!5m2!1sfr!2sfr" width="600" height="375" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
  </div>
</div>

app/views/comments/new.html.erb
<div class="contenu">
  <h3>Ajoutez votre "news" dans le champs ci-dessous</h3>
  <br>
  <br>
  <br>
  <%= simple_form_for(@comment) do |f| %>
    <div class="field">
      <%= f.input :content, label: "Contenu", type: "text" %>
    </div>
    <br>
    <br>
    <div class="form-actions">
      <%= f.submit 'Sauvegarder la News', class:'bnt btn-primary' %>
    </div>
  <% end %>


  <br>
  <br>
  <br>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MonsieurSyndic</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="bandeau">
  <div class="presentation">
    <%= image_tag("MSyndicLogo.png", alt: "logo") %>
    <div class="pitch">
      <div class="title">
        <h1 class='word1'>Monsieur</h1><h1 class='word2'>SYNDIC</h1>
      </div>
      <h2>Un cabinet éthique et novateur</h2>
      <p>Mon cabinet indépendant s’attache à développer un travail de qualité tout en valorisant la proximité et la disponibilité indispensables à notre métier de services. Mon organisation est renforcée d’une équipe autonome qui me suit depuis mes débuts, depuis mes premiers clients : la fidélité et la fiabilité de mes collaborateurs sont l’un des moteurs de mon entreprise à taille humaine.</p>
      <p>Chaque client est unique. Ce credo m’engage à adapter des solutions de services spécifiques et variées aux besoins de chacun d’entres eux. Mon personnel, qui partage la même culture d’entreprise, est à la recherche du détail, aidé en cela par un outil informatique performant asservi à nos besoins. Si je considère que c’est dans l’expérience que nous trouvons de nombreuses solutions, je reste attentive aux nouvelles méthodes de gestion, aux notions d’économies, aux comptes justes, aux travaux appropriés…</p>
      <p>Monsieur Syndic gère toutes les copropriétés, sans limite de nombre de lots.  Notre siège social est situé à Marseille afin de proposer un accès traditionnel à nos locaux pour nos clients des Bouches du Rhône comme du Var. Tous nos gestionnaires sont équipés pour être autonomes et surtout ils ont une mission principale : être sur le terrain et dans vos immeubles.</p>
      <p>L’interface de Monsieur Syndic est a ce point performante qu’elle fait oublier à nos clients comme à nos collaborateurs la nécessité de se déplacer en nos agences : notre bureau est votre copropriété, votre bureau est votre smartphone, votre tablette ou encore votre ordinateur.</p>
      <p>J’ai voulu Monsieur Syndic moderne pour ses clients, audacieux par ses moyens et ambitieux pour mes collaborateurs : nous ne cherchons pas être les premiers, nous cherchons à être les meilleurs.</p>
      <p>La présidente - Nathalie TRONCON</p>
    </div>
  </div>
</div>

app/views/pages/prices.html.erb
<h1>nos prix</h1>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<header id='navbar'>
  <div class='nav'>
    <%=link_to root_path do %>
    <div class='logo' id='logo-navbar'>
      <%= image_tag("MSyndicLogo.png", size: "90x90", alt: "logo") %>
      <div class="title">
        <h1 class='word1'>Monsieur</h1><h1 class='word2'>SYNDIC</h1>
      </div>
    </div>
    <%end%>
    <% if user_signed_in? %>
      <div class='logout'>
        <%= button_to destroy_user_session_path, method: :delete, class: "out-btn" do%>
          <i class="fa-solid fa-circle-xmark">log out</i>
        <% end %>
      </div>
    <% end %>
    <div class='menu'>
      <div class='buttons'>
        <%= link_to about_path do%>
          <button>
            <h3>Qui sommes-nous ?</h3>
          </button>
        <%end%>

        <a href="https://extranet2.ics.fr/V5/connexion-mrsyndic.html" target='blank'>
          <button>
            <h3>Accès client</h3>
          </button>
        </a>
        <button>
          <h3>Attestations</h3>
        </button>
        <%= link_to prix_path do%>
          <button>
            <h3>Nos prix</h3>
          </button>
        <%end%>
      </div>
    </div>
  </div>
</header>